server:
  port: 2222

spring:
  application:
    name: faas-lambda-service
  data:
    redis:
      url: redis://redis:6379
management:
  endpoints:
    web:
      exposure:
        include: health,metrics

app:
  lambda:
    memory-mb: 512
    max-retries: 3
    result-ttl-minutes: 10
    max-concurrent-invocations:
  queue-worker:
    enabled: true
    initial-delay: 5000
    timeout-seconds: 30
    max-worker-threads: 30
